---
# // encrypt using:
# $ ansible-vault encrypt files/*.keytab --vault-id keytabs@passwords
#
# // run using:
# $ ansible-playbook -i inventory keytabs.yml --vault-id keytabs@passwords
# or
# $ ansible-playbook -i inventory keytabs.yml --vault-password-file passwords
#
- hosts: all
  become: yes
  tasks:
    - name: keytab directory
      file:
        path: /etc/keytabs
        state: directory
    - name: copy keytab
      copy:
        src: "./files/{{ item.name }}"
        dest: /etc/keytabs/
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "u=wr,g=r,o-rwx"
        decrypt: yes
      with_items: "{{ keytabs }}"
