all:
  vars:
    ansible_user: pete
  children:
    web:
      hosts:
        pi1.mac.wales:
      vars:
        keytabs:
        - user1.keytab
        - user2.keytab
    db:
      hosts:
        pi3.mac.wales:
      vars:
        keytabs:
         - user1.keytab
