all:
  vars:
    ansible_user: pete
  children:
    web:
      hosts:
        pi1.mac.wales:
        pi3.mac.wales:
      vars:
        keytabs:
          - name: user1.keytab
            owner: oss
            group: oss
          - name: user2.keytab
            owner: oss
            group: oss
    db:
      hosts:
        pi4.mac.wales: 
      vars:
        ansible_user: pete
        keytabs:
          - name: user1.keytab
            owner: oss
            group: oss
